#INSERT INTO roles(name) VALUES('ADMIN');
#INSERT INTO roles(name) VALUES('SECRETARY');
#INSERT INTO roles(name) VALUES('SUNDAY_SCHOOL');
#INSERT INTO roles(name) VALUES('SEBEKA_GUBAE');
#INSERT INTO roles(name) VALUES('ABO_WENBER_SEBEKA_GUBAE');
