INSERT INTO roles(name) VALUES('ROLE_MEMBER');
INSERT INTO roles(name) VALUES('ROLE_SUPERADMIN');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_CASHIER');
INSERT INTO roles(name) VALUES('ROLE_SECRETARY');
INSERT INTO roles(name) VALUES('ROLE_NOTIFIER');