package com.Medhanialem.jwtauthentication.model;

public enum RequestOperationStatus {
	SUCCESS,ERROR,ENTER_NEW_PASSWORD_CANNOT_BE_EMPTY, CONFIRM_PASSWORD_CANNOT_BE_EMPTY,MISSING_REQUIRED_TOKEN, PASSWORDS_DO_NOT_MATCH 

}
